[project]
name = "sd-perturbed-attention"
description = "Perturbed-Attention Guidance and Smoothed Energy Guidance for ComfyUI and SD Forge/reForge."
version = "1.1.5"
license = { text = "MIT License" }

[project.urls]
Repository = "https://github.com/pamparamm/sd-perturbed-attention"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "pamparamm"
DisplayName = "sd-perturbed-attention"
Icon = ""
